### PR TITLE
[task_01]Add task 01

### PR DESCRIPTION
**Pull request by SergeyGalanin**

### CODE REVIEW

**Review by NogameNo-life — APPROVED** [review]

**Comment by SergeyGalanin** [comment]
:blush::yum::new_moon_with_face:

**Review by ElXoce — COMMENTED** [review]
🙏🙏🙏🚶‍♂️➡️🕍🚶‍♂️➡️🕍🚶‍♂️➡️🕍🚶‍♂️➡️🕍

**Review by ElGansoDorado — APPROVED** [review]
💪

**Review by ElXoce — APPROVED** [review]
🚱

**Pull request merged**
